apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
spec:
  type: LoadBalancer
  selector:
    app: monitoring-service
  ports:
    - protocol: TCP
      port: 8765
      targetPort: 8765
