eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka}
  instance:
    prefer-ip-address: true


spring:
  datasource:
    url: jdbc:postgresql://postgres-postgresql:5432/e-commerce
    username: postgres
    password: postgres

